# Generated by Django 3.2.5 on 2023-06-16 10:41

import api.models.users
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('realname', models.CharField(blank=True, max_length=255)),
                ('contactNumber', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(choices=[('1', '普通用户'), ('2', '维修人员'), ('3', '普通管理员'), ('4', '超级管理员')], default='1', max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bio', models.TextField(default='这个人很懒，这么久都还没填写信息', max_length=500)),
                ('gender', models.CharField(choices=[('O', 'Prefer Not to Say'), ('M', 'Male'), ('F', 'Female')], default='O', max_length=10)),
                ('m_type', models.CharField(choices=[('0', '无'), ('1', '水'), ('2', '电'), ('3', '机械')], default='0', max_length=10)),
                ('m_status', models.CharField(choices=[('0', '无'), ('1', '水'), ('2', '电'), ('3', '机械')], default='0', max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('dob', models.DateField(default=datetime.date(2000, 1, 1))),
                ('profile', models.ImageField(blank=True, upload_to=api.models.users.profile_to)),
                ('thumbnail', models.ImageField(blank=True, upload_to=api.models.users.thumbnail_to)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roomNumber', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('solution', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ic', models.CharField(max_length=20)),
                ('visitTime', models.DateTimeField()),
                ('contactNumber', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=8)),
                ('otp_sent', models.IntegerField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.house')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('real_name', models.CharField(blank=True, max_length=150)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('contactName', models.CharField(blank=True, max_length=150)),
                ('contactNumber', models.CharField(blank=True, max_length=150)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('accUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('contactName', models.CharField(max_length=50)),
                ('contactNumber', models.CharField(max_length=20)),
                ('repairingTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], default='Open', max_length=20)),
                ('plan', models.TextField(blank=True)),
                ('completeTime', models.DateTimeField(blank=True, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.house')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('solver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solver', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentalInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('fee', models.IntegerField()),
                ('nextDeadline', models.DateTimeField()),
                ('unpaid', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.house')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('rentalInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rentalinfo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='rentalInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentalInfo', to='api.rentalinfo'),
        ),
    ]
