# Generated by Django 3.2.5 on 2023-06-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230616_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='m_status',
            field=models.CharField(choices=[('0', '可用'), ('1', '不可用')], default='0', max_length=10),
        ),
    ]
