# Generated by Django 3.2 on 2023-06-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230617_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalinfo',
            name='nextManagementFeeDeadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
