# Generated by Django 3.2 on 2023-06-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230618_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalinfo',
            old_name='unpaid_management',
            new_name='ispaid_management',
        ),
        migrations.RenameField(
            model_name='rentalinfo',
            old_name='unpaid_rental',
            new_name='ispaid_rental',
        ),
        migrations.AddField(
            model_name='rentalinfo',
            name='lastPay',
            field=models.DateTimeField(null=True),
        ),
    ]
