# Generated by Django 3.2 on 2023-06-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20230619_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
