# Generated by Django 3.2 on 2023-06-19 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_payment_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to='api.house'),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_house', to='api.house'),
        ),
    ]
