# Generated by Django 3.2 on 2023-06-19 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20230619_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='accUser',
        ),
        migrations.AddField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belong_to_company', to='api.tenant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
