# Generated by Django 3.2 on 2023-06-20 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20230619_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitrequest',
            old_name='contactNumber',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='visitrequest',
            old_name='visitTime',
            new_name='visit_time',
        ),
    ]
