# Generated by Django 3.2 on 2023-06-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20230620_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='company',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
