# Generated by Django 3.2.5 on 2023-06-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_visitrequest_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
