# Generated by Django 3.2 on 2023-06-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_payment_paymenttime'),
        ('api', '0019_alter_visitrequest_inviter'),
    ]

    operations = [
    ]
