# Generated by Django 3.2 on 2023-06-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20230620_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='expect_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='expect_time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='expect_time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
