# Generated by Django 3.2 on 2023-06-20 16:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20230620_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.house')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rentalinfo')),
            ],
        ),
    ]
