# Generated by Django 3.2 on 2023-06-22 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_tenant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalinfo',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.house'),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='nextManagementFeeDeadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='nextRentalDeadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='paidManagementDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='paidRentalDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
