# Generated by Django 3.2 on 2023-06-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20230623_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
