# Generated by Django 3.2 on 2023-06-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_repair_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='type',
            field=models.CharField(choices=[('0', '空闲'), ('1', '已分派'), ('2', '智能推荐')], default='0', max_length=1),
        ),
    ]
