# Generated by Django 3.2.5 on 2023-06-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_timeslot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='repair',
            name='type',
            field=models.CharField(blank=True, choices=[('0', '未分类'), ('1', '水'), ('2', '电'), ('3', '机械')], default='0', max_length=10, null=True),
        ),
    ]
