# Generated by Django 3.2.5 on 2023-06-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20230625_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
