# Generated by Django 3.2.5 on 2023-06-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20230626_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='type',
            field=models.CharField(blank=True, choices=[('0', '未分类'), ('1', '水'), ('2', '电'), ('3', '机械')], default='0', max_length=10, null=True),
        ),
    ]
